FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# ดาวน์โหลด NLTK stopwords
RUN python - << 'EOF'
import nltk
nltk.download('stopwords')
EOF
